# 服务器端口设置
server:
  port: 8887

# github OAuth 配置
github:
  client:
    id: 3fb7925ca6ea019aed64
    secret: cf43f01fac54c7c6bbd86d0d4ddb85be5c513036
  redirect:
    uri: http://localhost:8887/callback

spring:
  # 数据库源配置
  datasource:
    url: jdbc:h2:~/communtiy
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

# User中的驼峰命名法和数据库的下划线命名法匹配
mybatis:
  configuration:
    map-underscore-to-camel-case: true
