# 开发环境的数据源
#spring:
#  # 数据库源配置
#  datasource:
#    url: jdbc:h2:~/communtiy
#    username: sa
#    password: 123
#    driver-class-name: org.h2.Driver
spring:
  # 数据库源配置
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC
    username: root
    password: 131452
    driver-class-name: com.mysql.cj.jdbc.Driver

# github OAuth 配置
github:
  client:
    id: 3fb7925ca6ea019aed64
    secret: cf43f01fac54c7c6bbd86d0d4ddb85be5c513036
  redirect:
    uri: http://localhost:8887/callback